//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bouldering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userLog
    {
        public string userID { get; set; }
        public string timeStamp { get; set; }
    }
}
